// PRODUCER — accepts incoming mail events over HTTP, publishes to Kafka.
//
// In production this lives BEHIND your SMTP/IMAP gateway: when a new mail
// lands for a user, the mail server POSTs it here, and this service writes
// it to the `notif.events` topic. Returns immediately — no waiting on
// downstream delivery. That's the whole point of Kafka in front: producer
// throughput is decoupled from delivery throughput.
//
// Endpoint: POST /publish  body = mail event (see SHAPE below)

const express = require('express');
const { v4: uuid } = require('uuid');
const { getProducer } = require('../shared/kafka');

const PORT = process.env.PORT || 4100;
const TOPIC = 'notif.events';

const app = express();
app.use(express.json({ limit: '2mb' }));

app.get('/health', (_, res) => res.json({ ok: true }));

// SHAPE:
//   { accountId, fromAddress, fromName, subject, body, priority?, groupKey? }
app.post('/publish', async (req, res, next) => {
  try {
    const evt = {
      id: req.body.id || uuid(),
      accountId: req.body.accountId,
      fromAddress: req.body.fromAddress,
      fromName: req.body.fromName || '',
      subject: req.body.subject || '',
      body: req.body.body || '',
      priority: req.body.priority || 'medium',
      groupKey: req.body.groupKey,         // optional: enables server-side coalesce
      receivedAt: Date.now(),
    };
    if (!evt.accountId) return res.status(400).json({ error: 'accountId required' });

    const producer = await getProducer();
    await producer.send({
      topic: TOPIC,
      messages: [{
        // ── KEY = accountId is the critical part. ────────────────────────────
        // Kafka guarantees per-partition ordering, so all events for one user
        // land on one partition and are processed in order by one fanout
        // worker. Different users go to different partitions and scale out.
        key: evt.accountId,
        value: JSON.stringify(evt),
        headers: { 'event-type': 'mail.new' },
      }],
    });

    res.json({ accepted: true, id: evt.id });
  } catch (err) { next(err); }
});

// Convenience: bulk burst endpoint for load testing the pipeline.
//   POST /burst?n=100&accountId=u1
app.post('/burst', async (req, res, next) => {
  try {
    const n = Math.min(parseInt(req.query.n) || 10, 5000);
    const accountId = req.query.accountId || 'u1';
    const producer = await getProducer();
    const messages = Array.from({ length: n }, (_, i) => ({
      key: accountId,
      value: JSON.stringify({
        id: uuid(),
        accountId,
        fromAddress: `loadtest${i % 5}@example.com`,
        subject: `Burst event #${i + 1}`,
        body: 'Generated by /burst',
        priority: 'medium',
        groupKey: 'burst:rolling',
        receivedAt: Date.now(),
      }),
    }));
    await producer.send({ topic: TOPIC, messages });
    res.json({ accepted: n });
  } catch (err) { next(err); }
});

app.use((err, _, res, __) => {
  console.error('[producer]', err);
  res.status(500).json({ error: err.message });
});

app.listen(PORT, () => console.log(`[producer] listening on :${PORT} → kafka topic ${TOPIC}`));
